version: "3.8"

services:
  db:
    image: mysql:8.0 #(Ổn định)
    container_name: gym_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME} # Tên DB tự động tạo ban đầu
      MYSQL_USER: ${DB_USER} # create user
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql # QUAN TRỌNG: Lưu dữ liệu ra ngoài để không mất khi tắt Docker
    command: --default-authentication-plugin=mysql_native_password # Fix lỗi connect cho một số client cũ

  # (Tùy chọn) Cài thêm Adminer (Giao diện web nhẹ) để check nhanh nếu lười bật DBeaver
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
